"""Short daily brief for a country: what is on the calendar, what people there
were engaged with, how that compares with the news and with the country's own
recent history.

Rules that keep it honest and cheap:
- Only real inputs go in (calendar rows, collected posts, live headlines) and the
  prompt forbids adding anything else. A number in the output that is not in the
  inputs makes the result fall back to a deterministic template.
- Raw top-liked posts are mostly noise ("[Audio: original sound ...]", hashtag
  walls, spam), so titles are cleaned and sampled evenly across platforms before
  a model sees them — better summaries and fewer tokens.
- A region needs MIN_SIGNALS collected posts that day AND MIN_CLEAN_TOPICS usable
  titles for a trend summary. Only ~13 of ~76 listed regions have real daily
  volume; the rest would produce a confident summary of nothing. Regions with
  calendar events but thin data get a calendar-only line.
- "Compared with usual" needs history: the 7-day baseline is only used once a
  region has MIN_BASELINE_DAYS prior days of data, otherwise the prompt says
  there is not enough history yet (never a made-up comparison).
- One small LLM call per region, skipped entirely when the inputs are unchanged
  since the last run (inputs_hash).
- Generated by the scheduler and cached, never on a page view.
"""
import hashlib
import json
import logging
import re
from datetime import date, datetime, timedelta

from app.collectors.region_codes import region_name

logger = logging.getLogger("culturix.services.region_daily_summary")

MIN_SIGNALS = 15
MIN_CLEAN_TOPICS = 4
MAX_TOPICS = 10
PER_PLATFORM = 3
UPCOMING_DAYS = 3
BASELINE_DAYS = 7
MIN_BASELINE_DAYS = 3
MAX_SUMMARY_CHARS = 320
MAX_SUMMARY_WORDS = 60
MAX_HEADLINES = 8

# Bump when build_prompt changes so cached rows are rewritten instead of skipped.
PROMPT_VERSION = 3

MOODS = ("celebratory", "playful", "curious", "tense", "somber", "angry", "neutral")
ALIGNMENTS = ("aligned", "diverged", "unknown")

_JUNK_PREFIXES = ("[audio:", "special:", "wikipedia:", "file:", "category:")
_JUNK_TITLES = {"main page", "メインページ", "accueil", "wikipédia", "hauptseite", "pagina principale", "portada"}


def day_bounds(day: date) -> tuple[datetime, datetime]:
    """Trend.collected_at is stored as naive UTC."""
    start = datetime(day.year, day.month, day.day)
    return start, start + timedelta(days=1)


# ── input cleaning ──────────────────────────────────────────────────────────

def clean_title(text: str | None) -> str | None:
    """A readable topic from a raw post title, or None when it is noise: audio
    tags, hashtag/mention-only text, wiki chrome, or too little real text."""
    if not text:
        return None
    raw = " ".join(text.split())
    if raw.lower().startswith(_JUNK_PREFIXES) or raw.lower() in _JUNK_TITLES:
        return None
    stripped = re.sub(r"https?://\S+|[#@]\S+", " ", raw)
    stripped = " ".join(stripped.split()).strip(" -–—|:;,.…")
    letters = re.sub(r"[\W\d_]+", "", stripped)
    if len(letters) < 12:
        return None
    return stripped[:140]


def _normalize_key(text: str) -> str:
    return re.sub(r"\W+", " ", text.lower()).strip()[:60]


def pick_topics(rows) -> list[dict]:
    """Cleaned, de-duplicated titles, at most PER_PLATFORM per platform (most-liked
    first) so one platform can't dominate, capped at MAX_TOPICS overall."""
    per_platform: dict[str, list[dict]] = {}
    seen = set()
    for row in rows:  # already ordered by likes desc
        title = clean_title(row.title or row.content)
        if not title:
            continue
        key = _normalize_key(title)
        if not key or key in seen:
            continue
        seen.add(key)
        bucket = per_platform.setdefault(row.platform, [])
        if len(bucket) < PER_PLATFORM:
            bucket.append({"title": title, "platform": row.platform, "likes": row.likes})
    # Round-robin across platforms, best-liked first within each.
    topics, depth = [], 0
    while len(topics) < MAX_TOPICS and any(len(b) > depth for b in per_platform.values()):
        for bucket in per_platform.values():
            if len(bucket) > depth and len(topics) < MAX_TOPICS:
                topics.append(bucket[depth])
        depth += 1
    return topics


# ── gathering ───────────────────────────────────────────────────────────────

def gather_baseline(session, region: str, day: date, signal_count: int, today_themes: list[str],
                    today_avg_likes: float | None) -> dict:
    """How today compares with this region's previous BASELINE_DAYS days."""
    from sqlalchemy import func
    from app.models.cluster import Cluster
    from app.models.region_daily_summary import RegionDailySummary
    from app.models.trend import Trend

    start = datetime(day.year, day.month, day.day) - timedelta(days=BASELINE_DAYS)
    end = datetime(day.year, day.month, day.day)
    per_day = (
        session.query(func.date(Trend.collected_at), func.count(Trend.id), func.avg(Trend.likes))
        .filter(Trend.region == region, Trend.collected_at >= start, Trend.collected_at < end)
        .group_by(func.date(Trend.collected_at)).all()
    )
    usable = [(n, likes) for _, n, likes in per_day if n >= MIN_SIGNALS // 2]
    recent_moods = [
        {"date": r.summary_date.isoformat(), "mood": r.mood, "sentiment": r.sentiment}
        for r in session.query(RegionDailySummary)
        .filter(RegionDailySummary.region == region, RegionDailySummary.summary_date < day,
                RegionDailySummary.summary_date >= day - timedelta(days=BASELINE_DAYS),
                RegionDailySummary.mood.isnot(None))
        .order_by(RegionDailySummary.summary_date.asc()).all()
    ]
    if len(usable) < MIN_BASELINE_DAYS:
        return {"enough": False, "days": len(usable), "recent_moods": recent_moods}

    avg_count = sum(n for n, _ in usable) / len(usable)
    likes_vals = [float(l) for _, l in usable if l is not None]
    avg_likes = sum(likes_vals) / len(likes_vals) if likes_vals else None

    def phrase(ratio: float | None, noun: str) -> str | None:
        if ratio is None:
            return None
        if ratio >= 1.25:
            return f"busier than usual: {noun} about {ratio:.1f}x the recent daily average"
        if ratio <= 0.8:
            return f"quieter than usual: {noun} about {ratio:.1f}x the recent daily average"
        return f"{noun} in line with the recent daily average"

    prior_themes = {
        t for (t,) in session.query(Cluster.theme).join(Trend, Trend.cluster_id == Cluster.id)
        .filter(Trend.region == region, Trend.collected_at >= start, Trend.collected_at < end,
                Cluster.theme.isnot(None)).distinct().all()
    }
    return {
        "enough": True, "days": len(usable),
        "volume": phrase(signal_count / avg_count if avg_count else None, "post volume"),
        "engagement": phrase(today_avg_likes / avg_likes if today_avg_likes and avg_likes else None, "average likes"),
        "new_themes": [t for t in today_themes if t not in prior_themes][:3],
        "recent_moods": recent_moods,
    }


def gather_inputs(session, region: str, day: date, headlines: list[dict] | None = None) -> dict:
    """Everything a summary may be built from, for one region and day."""
    from sqlalchemy import func, or_
    from app.models.calendar_event import CalendarEvent
    from app.models.cluster import Cluster
    from app.models.trend import Trend

    start, end = day_bounds(day)
    day_filter = (Trend.region == region, Trend.collected_at >= start, Trend.collected_at < end)
    signal_count = session.query(Trend).filter(*day_filter).count()
    avg_likes = session.query(func.avg(Trend.likes)).filter(*day_filter).scalar()

    rows = session.query(Trend).filter(*day_filter).order_by(Trend.likes.desc().nullslast(), Trend.id.desc()).limit(300).all()
    topics = pick_topics(rows)

    platforms = [
        p for p, _ in session.query(Trend.platform, func.count(Trend.id)).filter(*day_filter)
        .group_by(Trend.platform).order_by(func.count(Trend.id).desc()).all()
    ]
    themes = [
        t for t, _ in session.query(Cluster.theme, func.count(Trend.id)).join(Trend, Trend.cluster_id == Cluster.id)
        .filter(*day_filter, Cluster.theme.isnot(None)).group_by(Cluster.theme)
        .order_by(func.count(Trend.id).desc()).limit(4).all() if t
    ]

    events = []
    for ev in (
        session.query(CalendarEvent)
        .filter(CalendarEvent.date >= day, CalendarEvent.date <= day + timedelta(days=UPCOMING_DAYS),
                or_(CalendarEvent.regions.overlap([region]), CalendarEvent.regions.is_(None)))
        .order_by(CalendarEvent.date.asc()).all()
    ):
        delta = (ev.date - day).days
        events.append({
            "name": ev.name, "category": ev.category, "date": ev.date.isoformat(),
            "when": "today" if delta == 0 else f"in {delta} day{'s' if delta != 1 else ''}",
            # LLM-generated sports/music rows are expectations, not verified facts.
            "confirmed": ev.source != "llm_generated",
        })

    return {
        "region": region, "day": day, "signal_count": signal_count, "topics": topics,
        "platforms": platforms, "themes": themes, "events": events,
        "headlines": (headlines or [])[:MAX_HEADLINES],
        "baseline": gather_baseline(session, region, day, signal_count, themes, float(avg_likes) if avg_likes else None),
    }


# ── writing ─────────────────────────────────────────────────────────────────

def build_prompt(inputs: dict) -> str:
    country = region_name(inputs["region"])
    day: date = inputs["day"]
    cal = "\n".join(
        f"- {e['name']} ({e['category']}, {e['when']}{'' if e['confirmed'] else ', unverified expectation'})"
        for e in inputs["events"]
    ) or "none"
    signals = "\n".join(f"{i}. [{t['platform']}] {t['title']}" for i, t in enumerate(inputs["topics"], 1))
    news = "\n".join(f"- {h['title']}" + (f" ({h['source']})" if h.get("source") else "") for h in inputs["headlines"]) \
        or "not available"
    themes = ", ".join(inputs["themes"]) or "none detected"

    b = inputs["baseline"]
    if b.get("enough"):
        lines = [x for x in (b.get("volume"), b.get("engagement")) if x]
        if b.get("new_themes"):
            lines.append("themes new today (not seen in the past week): " + ", ".join(b["new_themes"]))
        history = "; ".join(lines) or "nothing notable versus the past week"
    else:
        history = f"not enough history yet ({b.get('days', 0)} usable prior days), so make no comparison with usual"
    moods = ", ".join(f"{m['date'][5:]}: {m['mood']}" for m in b.get("recent_moods", [])[-5:]) or "none recorded yet"

    return f"""You write the daily brief for {country} on {day.isoformat()} for a public world-culture atlas.

CALENDAR (real entries):
{cal}

TOP SOCIAL POSTS people in {country} engaged with ({inputs['signal_count']} collected, from platforms: {', '.join(inputs['platforms']) or 'n/a'}):
{signals}

THEMES detected: {themes}

LIVE NEWS HEADLINES in {country} right now:
{news}

VERSUS THE PAST WEEK: {history}
RECENT DAILY MOODS: {moods}

Write the brief in English: at most 3 short sentences and 50 words. Every sentence must end with a period.
1. Calendar: if an event is today or within 3 days, say so in plain words ("Respect for the Aged Day is in
   3 days."). If there is none, do NOT mention the calendar at all.
2. Name one or two CONCRETE subjects people engaged with (a person, show, sport, product, or event taken from
   the lists), never a vague category like "entertainment" or "a mix of content". Then, in the same sentence,
   say whether the news covers the same things or something different.
3. Only if the lists above support it, add a separate short sentence on how the day compares with usual
   ("Activity was busier than usual."). Never present the comparison as a consequence of the topics.
Rules: use only what is listed above. Do not invent events, causes, names, or numbers. Do not call anything
viral or trending unless it appears in the lists. No emojis, hashtags, or quotation marks. If the posts are
mostly noise, say so briefly instead of inventing a theme.

Also judge the day's overall feel from the posts and news:
- mood: one of {list(MOODS)}
- sentiment: integer -2 (very negative) to 2 (very positive)
- alignment: "aligned" if news and social cover similar subjects, "diverged" if clearly different, "unknown" if news is unavailable or unclear

Return ONLY valid JSON: {{"summary": "...", "mood": "...", "sentiment": 0, "alignment": "..."}}"""


def _allowed_text(inputs: dict) -> str:
    b = inputs["baseline"]
    parts = [inputs["day"].isoformat(), str(inputs["signal_count"])]
    parts += [t["title"] for t in inputs["topics"]] + inputs["themes"] + [h["title"] for h in inputs["headlines"]]
    parts += [f"{e['name']} {e['when']} {e['date']}" for e in inputs["events"]]
    parts += [b.get("volume") or "", b.get("engagement") or "", " ".join(b.get("new_themes", []))]
    return " ".join(parts)


def validate_summary(summary: object, inputs: dict) -> str | None:
    """The cleaned summary, or None if it can't be trusted: empty, too long, or
    containing a number that appears nowhere in the inputs."""
    if not isinstance(summary, str):
        return None
    text = " ".join(summary.split()).strip()
    if text and text[-1] not in ".!?。！？":
        text += "."
    if not text or len(text) > MAX_SUMMARY_CHARS or len(text.split()) > MAX_SUMMARY_WORDS:
        return None
    allowed = set(re.findall(r"\d+", _allowed_text(inputs)))
    if any(n not in allowed for n in re.findall(r"\d+", text)):
        return None
    return text


def parse_feel(parsed: dict) -> dict:
    """mood / sentiment / alignment from the model, coerced to the allowed values."""
    mood = str(parsed.get("mood") or "").strip().lower()
    alignment = str(parsed.get("alignment") or "").strip().lower()
    try:
        sentiment = max(-2, min(2, int(parsed.get("sentiment"))))
    except (TypeError, ValueError):
        sentiment = None
    return {
        "mood": mood if mood in MOODS else None,
        "sentiment": sentiment,
        "alignment": alignment if alignment in ALIGNMENTS else "unknown",
    }


def _clip(text: str, limit: int) -> str:
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def template_summary(inputs: dict, include_signals: bool = True) -> str:
    """Deterministic fallback built only from real titles and calendar rows."""
    country = region_name(inputs["region"])
    today = [e["name"] for e in inputs["events"] if e["when"] == "today"]
    soon = [f"{e['name']} ({e['when']})" for e in inputs["events"] if e["when"] != "today"]
    parts = []
    if today:
        parts.append(f"Today in {country}: {', '.join(today)}.")
    if soon:
        parts.append(f"Coming up: {', '.join(soon[:2])}.")
    if include_signals and inputs["topics"]:
        titles = "; ".join(_clip(t["title"], 60) for t in inputs["topics"][:3])
        parts.append(f"Most engaged with: {titles}.")
    return _clip(" ".join(parts), MAX_SUMMARY_CHARS)


def inputs_hash(inputs: dict) -> str:
    payload = {
        "day": inputs["day"].isoformat(), "topics": [t["title"] for t in inputs["topics"]],
        "headlines": [h["title"] for h in inputs["headlines"]], "events": inputs["events"],
        "themes": inputs["themes"], "baseline": inputs["baseline"], "prompt": PROMPT_VERSION,
    }
    return hashlib.sha1(json.dumps(payload, sort_keys=True, ensure_ascii=False).encode()).hexdigest()


def _write_with_llm(inputs: dict) -> tuple[str, dict] | None:
    # Shared Qwen/Claude JSON call (with its one transient-failure retry).
    from app.services.culturix_ingestion import IngestionError, _call_llm_json

    try:
        parsed = _call_llm_json(build_prompt(inputs), temperature=0.3, max_tokens=350)
    except IngestionError as exc:
        logger.warning("Region summary LLM call failed for %s: %s", inputs["region"], exc)
        return None
    text = validate_summary(parsed.get("summary"), inputs)
    return (text, parse_feel(parsed)) if text else None


def generate_region_summary(session, region: str, day: date, force: bool = False, use_llm: bool = True,
                            news_fetcher=None):
    """Upserts and returns the summary row for (region, day), or None when there
    is neither enough trend data nor a calendar event to say anything true.
    News is a live lookup, so it is only fetched for today; past days are
    written without it."""
    from app.models.region_daily_summary import RegionDailySummary

    region = region.strip().upper()
    existing = session.query(RegionDailySummary).filter_by(region=region, summary_date=day).first()
    if existing and not force:
        return existing

    if news_fetcher is None:
        from app.collectors.news import fetch_country_headlines as news_fetcher
    headlines = news_fetcher(region, MAX_HEADLINES) if day == datetime.utcnow().date() else []

    inputs = gather_inputs(session, region, day, headlines)
    enough = inputs["signal_count"] >= MIN_SIGNALS and len(inputs["topics"]) >= MIN_CLEAN_TOPICS
    if not enough and not inputs["events"]:
        return None

    digest = inputs_hash(inputs)
    if existing and existing.inputs_hash == digest and existing.source != "template":
        return existing  # nothing changed since the last run: no LLM call

    feel = {"mood": None, "sentiment": None, "alignment": None}
    if enough:
        written = _write_with_llm(inputs) if use_llm else None
        if written:
            text, feel = written[0], written[1]
            source = "ai"
        else:
            text, source = template_summary(inputs), "template"
    else:
        text, source = template_summary(inputs, include_signals=False), "calendar"

    row = existing or RegionDailySummary(region=region, summary_date=day)
    row.summary = text
    row.source = source
    row.signal_count = inputs["signal_count"]
    row.platforms = inputs["platforms"]
    row.calendar = inputs["events"]
    row.topics = [t["title"] for t in inputs["topics"][:5]] if enough else []
    row.news = [h["title"] for h in inputs["headlines"]]
    row.baseline = inputs["baseline"]
    row.mood, row.sentiment, row.alignment = feel["mood"], feel["sentiment"], feel["alignment"]
    row.inputs_hash = digest
    if not existing:
        session.add(row)
    session.commit()
    return row


def regions_to_summarize(session, day: date) -> list[str]:
    """Regions with enough trend rows that day, plus any with a calendar event."""
    from sqlalchemy import func
    from app.models.calendar_event import CalendarEvent
    from app.models.trend import Trend

    start, end = day_bounds(day)
    rows = (
        session.query(Trend.region, func.count(Trend.id))
        .filter(Trend.region.isnot(None), Trend.collected_at >= start, Trend.collected_at < end)
        .group_by(Trend.region).having(func.count(Trend.id) >= MIN_SIGNALS).all()
    )
    regions = {r for r, _ in rows if len(r) == 2}
    for ev in session.query(CalendarEvent).filter(CalendarEvent.date >= day, CalendarEvent.date <= day + timedelta(days=UPCOMING_DAYS)).all():
        regions.update(r for r in (ev.regions or []) if len(r) == 2)
    return sorted(regions)


def generate_all_summaries(session, day: date, force: bool = True, use_llm: bool = True) -> dict:
    """One summary per eligible region for `day`. One region failing never stops
    the rest. Returns counts by outcome."""
    counts = {"ai": 0, "template": 0, "calendar": 0, "skipped": 0, "failed": 0}
    for region in regions_to_summarize(session, day):
        try:
            row = generate_region_summary(session, region, day, force=force, use_llm=use_llm)
        except Exception:
            session.rollback()
            logger.exception("Region summary failed for %s", region)
            counts["failed"] += 1
            continue
        counts[row.source if row else "skipped"] += 1
    return counts
