from datetime import datetime

from sqlalchemy import Column, Date, DateTime, Integer, JSON, String, Text, UniqueConstraint

from app.db import Base


class RegionDailySummary(Base):
    """One short, cached daily brief per country per day (see
    app/services/region_daily_summary.py). Generated by the scheduler — never
    on a public page view, so an anonymous visitor can't trigger LLM spend.

    `source` says how the text was made: "ai" (LLM, validated), "template"
    (deterministic, from real titles, when the LLM failed or stated something
    the inputs don't support), or "calendar" (a day with calendar events but
    too little trend data for an honest trend summary). `calendar`, `topics`,
    `news` and `baseline` keep the exact inputs so any summary can be audited.

    `mood`/`sentiment` are the day's overall feel (an LLM judgement stored per
    day so later days can be compared against the region's own recent history —
    no free per-country news-tone API was usable, see app/collectors/news.py).
    `inputs_hash` lets a re-run skip the LLM when nothing has changed."""
    __tablename__ = "region_daily_summaries"
    __table_args__ = (UniqueConstraint("region", "summary_date", name="uq_region_daily_summary"),)

    id = Column(Integer, primary_key=True, index=True)
    region = Column(String(2), nullable=False, index=True)
    summary_date = Column(Date, nullable=False, index=True)
    summary = Column(Text, nullable=False)
    source = Column(String(10), nullable=False)  # ai | template | calendar
    signal_count = Column(Integer, nullable=False, default=0)
    platforms = Column(JSON, nullable=True)   # ["tiktok", "youtube", ...]
    calendar = Column(JSON, nullable=True)    # [{"name", "category", "date", "when", "confirmed"}]
    topics = Column(JSON, nullable=True)      # the top signal titles the summary was written from
    news = Column(JSON, nullable=True)        # headlines compared against (audit only, not exposed publicly)
    baseline = Column(JSON, nullable=True)    # {"enough", "volume", "engagement", "new_themes", "recent_moods"}
    mood = Column(String(12), nullable=True)  # celebratory | playful | curious | tense | somber | angry | neutral
    sentiment = Column(Integer, nullable=True)  # -2 (very negative) .. +2 (very positive)
    alignment = Column(String(10), nullable=True)  # aligned | diverged | unknown — news vs social
    inputs_hash = Column(String(40), nullable=True)
    # Real, currently-generated audience archetypes (app/models/persona.py — this platform's own
    # cross-trend clustering, not available on any raw social feed) whose stated interests best match
    # what is trending here today: [{"name", "description", "content_angle", "score"}]. Computed
    # deterministically (cosine similarity over Voyage.ai embeddings), never by the summary LLM call —
    # see region_daily_summary.py::top_persona_matches. [] when nothing matched well enough.
    audience_matches = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
